services:
  db:
    container_name: profiles-db
    image: postgres:15
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5435:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 10s
      retries: 5

  migrations:
    build: .
    container_name: migrations-tool
    command: sh -c "alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  app:
    build:
      context: .
    container_name: profiles-service
    env_file:
      - .env
    ports:
      - 8001:8001
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host=0.0.0.0 --port=8001"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

volumes:
  pgdbdata:

networks:
  default:
    external:
      name: agronetwork