
services:
  db:
    container_name: profiles-db
    image: postgres:15
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env
    ports:
      - 5435:5432


  app:
    build:
      context: .
    container_name: profiles-service
    env_file:
      - .env
    ports:
      - 8001:8001
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host=0.0.0.0 --port=8001"
    depends_on:
      db:
        condition: service_healthy


volumes:
  pgdbdata:

networks:
  default:
    external:
      name: agronetwork